### PR TITLE
Add enforcer rule for file encoding

### PR DESCRIPTION
**Pull request by maddingo**
The enforcer rule guesses the file encoding and matches it against project.build.sourceEncoding

### CODE REVIEW

**Comment by mfriedenhagen** [comment]
Hello @maddingo, 
* unfortunately your source code is not formatted to the current standards of Mojohaus, we use the same style as [Apache Maven](https://maven.apache.org/developers/conventions/code.html).
* It would be really great if you could add documentation as well.

**Comment by maddingo** [comment]
Hei @mfriedenhagen, I applied the code format to the code and added, integration tests and documentation. Are there any more improvements I should add?

**Comment by mfriedenhagen** [comment]
Hello @maddingo: It seems you did merge the current master which will make for  a strange flow, I will  rebase and squash all of your changes against the current master.

**Comment by mfriedenhagen** [comment]
Thanks @maddingo

**Pull request closed without merging**
