### PR TITLE
Option for ignore module-info.class

### PR DESCRIPTION
**Pull request by slawekjaranowski**
There is situation where we need ban dependency with module-info.class, so option to not exclude it will be helpful.
Now module-info.class is always skipped.

Default value to true don't change behavior.

### CODE REVIEW

**Comment by rfscholte** [comment]
this requires a jira ticket, because it is a new option, hence a new feature.
And I prefer to implement it with an integer, so you can define if the module-info is compatible with at version version X (and maybe use -1 to ignore it)

**Review by rfscholte — CHANGES_REQUESTED** [review]
See conversation

**Comment by slawekjaranowski** [comment]
Where is jira project for it ... I can't find

module-info is compatible for jdk >= 9 so I can't imagine what number user can provide. Now in code we have hardcoded version < 53 for this behavior.

Of course I don't want to change current functionality.

**Comment by rfscholte** [comment]
O wait, this is a mojohaus enforcer rule. In that case there's indeed no jira.

regarding the compatiblity: suppose you want your project to be java 9 compatible, but one of your dependencies has a module-info.class that was compiled for java 15. In that case you want this rule to break the build. You cannot assume that the module-info was compiled with exactly the same bytecodeversion as the rest of the code, so you check check it as well.

In the end it all depends if it will run on the modulepath or classpath.

**Comment by slawekjaranowski** [comment]
I don't change code which is responsible fot checking class bytecode  compatible - it will be as is.
 
I change code, which add module-info to list of ignore for checking. 

In simple way, scenario for current behavior:

1. I want to project be jdk [9,..) compatible so all class also module-info must be compatible with jdk [9,...) - and work in this way.

2. I want to project be jdk (..,7,8] compatible so all class also module-info must be compatible with jdk (..,7,8] - in this scenarion modul-info is excluded from checking

After my change scenario 1 is the same.

But scenario 2 fail - it is not important for me which jdk was used to build module-info, in the fact will be greter then jdk 8 because doesn't exist in jkd < 9

**Comment by rfscholte** [comment]
It makes sense to say that you want your classes to be Java 8 compatible AND the module descriptor java 11 compatible. So what you want is that non of the module descriptors has been targeted for Java 12 or above.

**Comment by slawekjaranowski** [comment]
No, simply everything must be compatible with **one** selected jdk version.

If I want to run application on jdk 8 - I want sure that no element require jdk greater then 8.

**Comment by rfscholte** [comment]
You're only thinking about applications, not libraries. Having a second thought. If YOUR project doesn't have a module descriptor, then there's no need to verify other module descriptors. No need for a new flag.

**Comment by slawekjaranowski** [comment]
My real example: I have some legacy application deployed on JBoss 5 with jdk8. When there is any module-info in application classpath, JBoss 5 don't deploy application any more - there is some mechanizm for aop/bytecode which is used during deployment for scaning j2ee component.

I don't want to investigate JBoss5 deployment and I don't want/ I can't  to upgrade JBoss.

Form my perspective it will be very useful if I can check all component  during build to have sure if nothing outside jdk 8 exist on classpatch also module-info.

Now I have strange error during deployment and finding cause of errors are some magic.

**Comment by rfscholte** [comment]
Okay, I know this issue from other containers. But what you're doing right now is abusing the `enforceBytecodeVersion` where you actually need something like a `banClasses` or `banResources`.

**Comment by slawekjaranowski** [comment]
banClasses, banResources will be ok I will think about it

**Comment by slawekjaranowski** [comment]
But from other side current implementation with skipping module-info look like workaround for wrong created artifact.

From JEP-238 Multi-Release JAR - I recognized that in case where all code is for jdk 8 and only module-info is for jdk 9 then module-info should be placed in META-INF/versions/9

**Comment by rfscholte** [comment]
You MAY put a module-info descriptor per `META-INF/release/x`, but it is allowed to have a module-descriptor in the root. It will be ignored on the classpath (the trick is the `-` in its name, which makes it an invalid Class name). What you see with old class-scanner, is that they scan for EVERY .class in a jar. This means that they will always have issues with the module-descriptor.class, but most likely also with every release-specific class.

**Pull request closed without merging**
