### PR TITLE
Recognize JDK 24

### PR DESCRIPTION
**Pull request by wendigo**
Class file version as in the: https://github.com/openjdk/jdk/blob/8908812d0a64f25f0d033d44725a69348789b223/src/jdk.compiler/share/classes/com/sun/tools/javac/jvm/ClassFile.java#L131

### CODE REVIEW

**Comment by cstamas** [comment]
LGTM

@slawekjaranowski @gnodet

**Review by slawekjaranowski — APPROVED** [review]

**Comment by mbien** [comment]
https://github.com/mojohaus/extra-enforcer-rules/blob/5fb6cf2d91ee4e0eddf74ea7fd6e6b57aa725fed/src/main/java/org/codehaus/mojo/extraenforcer/dependencies/EnforceBytecodeVersion.java#L145-L149
is going to fail once JDK 45 is released :D

**Comment by wendigo** [comment]
@mbien I will be retired by then (at least I hope so) ;)

**Comment by wendigo** [comment]
@mbien and if the Valhalla is delivered before that, this should work :)

**Pull request merged**
